### ISSUE TITLE
Example configuration is confusing

### ISSUE THREAD

**Issue by moritz1000** [raydak-labs/configarr#100]
Hello,

I just had a look at https://configarr.raydak.de/docs/configuration/config-file#configyml

and I find it confusing that the configuration example is mainly focusing on a Sonarr (TV) instance but at the same time contains [a custom format (IMAX Enhanced)](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#imax-enhanced) - that is designed for Radarr (Movies) - inside the Sonarr configuration:

```yaml
# Sonarr Configuration
sonarr:
  instance1: # Instance name (can be any unique identifier)
[...]
```

```yaml
[...]
    custom_formats: # Custom format assignments
      - trash_ids:
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to: # quality_profiles is deprecated
          - name: ExampleProfile
            score: 0
    quality_profiles:
      - name: Remux + WEB 1080p
        upgrade:
          min_format_score: 10000

# Radarr Configuration empty
radarr: {}
```

I would rather use a custom format for Sonarr (TV) https://trash-guides.info/Sonarr/sonarr-collection-of-custom-formats/
