### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'radarr')

### ISSUE THREAD

**Issue by etcg** [raydak-labs/configarr#162]
Hello,

I am currently using Notifiarr to sync TRaSH-Guides, but I would like to switch to Configarr. Unfortunately, I’m unable to get it working. I’m running it as a docker container (latest version) on Unraid (7.0.0) and encounter the following error:
```
/app/index.js:43977
    radarr: mappedCustomFormats(input.radarr),
                                      ^

TypeError: Cannot read properties of null (reading 'radarr')
    at transformConfig (/app/index.js:43977:39)
    at getConfig (/app/index.js:43934:12)
    at run (/app/index.js:44604:24)
    at Object.<anonymous> (/app/index.js:44633:1)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)

Node.js v22.12.0
```

I have tried every possible config.yml configuration, currently reduced to the absolute minimum documentation example for testing purposes, but the error remains the same each time. Below is my current testing configuration:
```
# With this options you can disable or enable processing for *arrs. Default is enabled
#sonarrEnabled: false
radarrEnabled: false
whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

sonarr:
  sonarr1:
    base_url: !secret SONARR_URL
    api_key: !secret SONARR_API_KEY

    quality_definition:
      type: series

    include:
      - template: 72dae194fc92bf828f32cde7744e51a1
        source: TRASH
```
Is this an unraid thing or a wrong config?
