### ISSUE TITLE
Add Trash Custom Format Groups?

### ISSUE THREAD

**Issue by jarama** [raydak-labs/configarr#185]
Hi, thanks for your amazing piece of software! Saves me a lot of time to manually update my container settings based on the trash guides.

I was wondering if I can also include Trash Custom Format Groups in the config yml?

I'd like to add all of the following radarr Custom Formats to my container: https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/movie-versions-noremux.json

However, when I try to add the trash-id for this cf group to my config yml, it does not work. Therefore I added all underlying cf's in my config as such:

```
custom_formats: # Custom format assignments
      - trash_ids:
          - d6e9318c875905d6cfb5bee961afcea9 # Language: Original Only
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: HD Bluray + WEB
```

However, it would be great if we could do it as following. Not only to make the config file smaller, but also to allow for the automatic import of different underlying custom formats if the content of the custom format group changes:

```
custom_formats: # Custom format assignments
      - trash_ids:
          - d6e9318c875905d6cfb5bee961afcea9 # Language: Original Only
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - bf033fe44d9b84aa6eceba6d0e27a88e # Movie Versions (Non-Remux Profiles)
        assign_scores_to:
          - name: HD Bluray + WEB
```

**Comment by BlackDark** [comment]
Hi @jarama, yes at the moment CustomFormatGroups are not supported.
But I already investigating the best way and usage to implement them to support everything from what TRaSH-Guide offers :)

**Comment by BlackDark** [comment]
Hi  @jarama first draft testing the groups. You can try it with following image: `ghcr.io/raydak-labs/configarr:dev-feat-cf-groups@sha256:c95caad5f2602aa43d601bf16776a30e4b00d356bf904ce500ad373f27dad60c`

Checkout the PR there you can find also a temporary documentation.

**Comment by jarama** [comment]
> Where do you mean that I can find the new temporary docs?

Ah, never mind… [found it](https://3047b2be.configarr-preview.pages.dev/docs/configuration/config-file)

**Comment by jarama** [comment]
I tested it and it seems to work as expected. Many of the cf-group profiles actually include only `"required": false` cfs. As such, for these cf-groups you still have to manually add all underlying cfs to the config yml, right? I think there is also a use case (at least there is for me), to include an extra argument in the config yml that also add the non-required cfs of the cf-groups. For example:
```
sonarr:
  instance1:
    # ...

    # (experimental) since v1.12.0
    # allows using the cf-groups from TRaSH-Guide. Only required ones will be loaded. Optional(required=false) ones can be added separately via custom_formats
    custom_format_groups:
      - trash_ids:
          - c4735e1d02e8738044ad4ad1bf58670c # Multiple CFs, only where required=true are loaded by default
        include_unrequired: false # set to true to load all CFs of cf-group, even when required=false
        assign_scores_to:
          - name: MyProfile
```

**Comment by BlackDark** [comment]
@jarama have added the extra parameter and readjusted some namings

````yml
    custom_format_groups:
      - trash_guide:
          - id: c4735e1d02e8738044ad4ad1bf58670c # Multiple CFs, default only required=true are loaded
            #include_unrequired: true # if you want to load all set this to true
        assign_scores_to:
          - name: ExampleProfile
````

**Comment by jarama** [comment]
Thanks! I tried it by pulling the image `ghcr.io/raydak-labs/configarr:dev-feat-cf-groups`, is that correct?

As a test I then removed one of the underlying cfs in radarr that I already had in there, but kept the rest of the underlying cfs of the cf-group. The docker ran without errors, but it left the cfs untouched (as indicated in the log).

This is what I added to the config (and I removed all lines about the underlying cfs of this cf-group):
```
    custom_format_groups:
      - trash_guide:
          - id: bf033fe44d9b84aa6eceba6d0e27a88e # Movie Versions (Non-Remux Profiles) (Optional)
            include_unrequired: true # if you want to load all set this to true
        assign_scores_to:
          - name: HD Bluray + WEB
```

Is this a bug, or did I pull the wrong container version?

**Comment by BlackDark** [comment]
Ah sorry, updated the images now. Last CI run had failed:
Please pull the new version of the image: `ghcr.io/raydak-labs/configarr:dev-feat-cf-groups`
Should work now

**Comment by jarama** [comment]
Perfect, it indeed works now! Thanks :)

As a side note: at the same time as when I included the cf-group, I also removed another unrelated cf from my config, but this cf still remains present in Radarr (both as a cf and in the quality profile). Is that expected behaviour?

**Comment by BlackDark** [comment]
You have to enable the reset of scores if not managed anymore: 

like: 

```yml
    quality_profiles:
      - name: HD Bluray + WEB
        # Support added with 1.7.0. Not support in all *arr applications. Check the application if it is supported.
        language: Any # The name must match available names in *arr
        # Reset existing CustomFormats scores on profile
        reset_unmatched_scores:
          enabled: true
```
