### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by jmaximusix** [raydak-labs/configarr#188]
For some reason it always crashes while trying to access the TRaSH guides. My internet connection is perfectly stable and definitely can resolve github.com. It also never fails on the first step (Checking Recyclarr repo)

So what's going on here?

```
INFO  [05:37:02.930]: Checking Recyclarr repo ...
INFO  [05:37:05.269]: Recyclarr repo: ref[master], hash[aee0a4108c5cfc11b57bb91ee6659d5bb7b87e43], path[/app/repos/recyclarr-config]
INFO  [05:37:05.269]: Checking TRaSH-Guides repo ...
INFO  [05:37:05.272]: Freshly cloned repository: 'https://github.com/TRaSH-Guides/Guides' at 'master'
/app/index.js:31838
        return { error: new GitError(void 0, error.toString("utf-8")) };
                        ^

GitError: Cloning into '/app/repos/trash-guides'...
fatal: unable to access 'https://github.com/TRaSH-Guides/Guides/': Could not resolve host: github.com

    at Object.action (/app/index.js:31838:25)
    at PluginStore.exec (/app/index.js:31874:25)
    at /app/index.js:28824:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/app/index.js:28822:16)
    at GitExecutorChain.<anonymous> (/app/index.js:28806:44)
    at Generator.next (<anonymous>)
    at fulfilled (/app/index.js:27527:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  task: {
    commands: [
      'clone',
      'https://github.com/TRaSH-Guides/Guides',
      '/app/repos/trash-guides'
    ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}

Node.js v22.13.1
```

**Comment by BlackDark** [comment]
Hi @jmaximusix, maybe would be best to describe your Setup (Container, DNS, Network) here instead of the discord channel so other people if getting similar problems in the future can search it up here.

For reference linking the TRaSH-Guide Discord Ticket: https://discord.com/channels/492590071455940612/1336932587553296425

**Comment by jmaximusix** [comment]
Thanks for the reply
- I'm running docker on an arch linux server, nothing special about the specs I think
- latest (I just pulled it for the first time yesterday), so 1.11.0
- yeah nslookup works, I had tested that before

My `docker-compose.jobs.yml` is this:

```
services:
  configarr:
    image: ghcr.io/raydak-labs/configarr:latest
    networks:
      - media_networrk
    user: 1000:1000
    environment:
      - TZ=Europe/Berlin
      # - DRY_RUN=true
    volumes:
      - ./configarr/config:/app/config
      - ./configarr/cfs:/app/cfs
      - ./configarr/templates:/app/templates
      - ./configarr/repos:/app/repos

networks:
  media_networrk:
    external: true
```

and my `config.yml` is this:

```
radarr:
  instance1:
    base_url: http://radarr:7878
    api_key: !secret RADARR_API_KEY

    quality_definition:
      type: movies

    include:
      - template: 425da1ba30711b55d2eb371437ec98d7
        source: TRASH
```

so really nothing special yet, I just wanted to fire it up for the first time

I admit this bug is very strange and appears to happen within the library instead of your code, yet I would still really like a solution to this 😅 

`git clone` also works inside the container and it also doesn't fail on the recyclarr git download which should be literally the same.
