### ISSUE TITLE
Custom Format Groups with score

### ISSUE THREAD

**Issue by kephasdev** [raydak-labs/configarr#196]
Hi, would it be possible to override the `score` in the `assign_scores_to` for `custom_format_groups`?

Something like this :
```
custom_format_groups:
  - trash_guide:
      - id: b4b4f2aa25c96620b73a01e6242f9dd2 # [Streaming Services] Anime
      - id: 35fb4585dcd9e2a5ac732e4309f5a45a # [Streaming Services] Asian
      - id: f60f4401ce880aad62e9d21c8bb6b91a # [Streaming Services] Dutch
      - id: 848fd356c200568fc5a6248150e7e7ea # [Streaming Services] French
      - id: 7832db22b71ab669458c17a2850d6913 # [Streaming Services] Miscellaneous
      - id: ddab3095a5d2f436f369263840af34f9 # [Streaming Services] UK
    assign_scores_to:
      - name: myprofile
        score: 0
```

So that the score for all the CFs would be at a specified value.

Thanks!

**Comment by BlackDark** [comment]
I am not sure if this would really make sense because in those CFs have different scores (mostly?). So not sure if does make for the average user to adjust them to one specific value. Or what kind of benefit do you see in providing such feature?

**Comment by btTeddy** [comment]
Would be great to have this added.
Some CFs like streaming services names are very useful for file naming just to preserve information where the release came from. 
Not necessarily need to be scored in every use case scenario.

All of this:
```
      - trash_ids:

          # Anime Streaming Services
          - 3e0b26604165f463f3e8e192261e7284 # CR
          - 1284d18e693de8efe0fe7d6b3e0b9170 # FUNi
          - 44a8ee6403071dd7b8a3a8dd3fe8cb20 # VRV
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - d34870697c9db575f17700212167be23 # NF
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - d54cd2bf1326287275b56bccedb72ee2 # ADN
          - 7dd31f3dee6d2ef8eeaa156e23c3857e # B-Global
          - 4c67ff059210182b59cdd41697b8cb08 # Bilibili
          - 570b03b3145a25011bf073274a407259 # HIDIVE
          - a370d974bc7b80374de1d9ba7519760b # ABEMA
          # UK Streaming Services
          - bbcaf03147de0f73be2be4a9078dfa03 # 4OD
          - fcc09418f67ccaddcf3b641a22c5cfd7 # ALL4
          - dc503e2425126fa1d0a9ad6168c83b3f # IP
          - fa5a16b951004c23e980d2913694a137 # ITVX
          - 9f72dc1059a6b277c21cee6a1f15f13f # MY5
          - b66a699fba6f9df91becab798d7502e5 # NOW
          # Misc Streaming Services
          - e6e299075e22ac8f541f722254c8350a # AUBC
          - defb0b4c8b3f6a15927c0f14c6e69c94 # CBC
          - 4e9a630db98d5391aec1368a0256e2fe # CRAV
          - fb1a91cdc0f26f7ca0696e0e95274645 # OViD
          - 3ac5d84fce98bab1b531393e9c82f467 # QIBI
          - c30d2958827d1867c73318a5a2957eb1 # RED
          - fe4062eac43d4ea75955f8ae48adcf1e # STRP
          # French Streaming Services
          - b0d6195c23ae254932da00512db7e8a8 # AUViO
          - f27d46a831e6b16fa3fee2c4e5d10984 # MyCANAL
          - 0455d6519a550dbf648c97b56e7231d2 # SALTO
        assign_scores_to:
          - name: WEB-2160p
            score: 0
```

Could be replaced just by a few lines  
```
custom_format_groups:
  - trash_guide:
      - id: b4b4f2aa25c96620b73a01e6242f9dd2 # [Streaming Services] Anime
      - id: ddab3095a5d2f436f369263840af34f9 # [Streaming Services] UK
      - id: 7832db22b71ab669458c17a2850d6913 # [Streaming Services] Miscellaneous
      - id: 848fd356c200568fc5a6248150e7e7ea # [Streaming Services] French
    assign_scores_to:
      - name: WEB-2160p
        score: 0
```

**Comment by btTeddy** [comment]
> I am not sure if this would really make sense because in those CFs have different scores (mostly?). So not sure if does make for the average user to adjust them to one specific value. Or what kind of benefit do you see in providing such feature?

Would be great to have this added.
Some CFs like streaming services names are very useful for file naming just to preserve information where the release came from. 
Not necessarily need to be scored in every use case scenario.

All of this:
```
      - trash_ids:

          # Anime Streaming Services
          - 3e0b26604165f463f3e8e192261e7284 # CR
          - 1284d18e693de8efe0fe7d6b3e0b9170 # FUNi
          - 44a8ee6403071dd7b8a3a8dd3fe8cb20 # VRV
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - d34870697c9db575f17700212167be23 # NF
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - d54cd2bf1326287275b56bccedb72ee2 # ADN
          - 7dd31f3dee6d2ef8eeaa156e23c3857e # B-Global
          - 4c67ff059210182b59cdd41697b8cb08 # Bilibili
          - 570b03b3145a25011bf073274a407259 # HIDIVE
          - a370d974bc7b80374de1d9ba7519760b # ABEMA
          # UK Streaming Services
          - bbcaf03147de0f73be2be4a9078dfa03 # 4OD
          - fcc09418f67ccaddcf3b641a22c5cfd7 # ALL4
          - dc503e2425126fa1d0a9ad6168c83b3f # IP
          - fa5a16b951004c23e980d2913694a137 # ITVX
          - 9f72dc1059a6b277c21cee6a1f15f13f # MY5
          - b66a699fba6f9df91becab798d7502e5 # NOW
          # Misc Streaming Services
          - e6e299075e22ac8f541f722254c8350a # AUBC
          - defb0b4c8b3f6a15927c0f14c6e69c94 # CBC
          - 4e9a630db98d5391aec1368a0256e2fe # CRAV
          - fb1a91cdc0f26f7ca0696e0e95274645 # OViD
          - 3ac5d84fce98bab1b531393e9c82f467 # QIBI
          - c30d2958827d1867c73318a5a2957eb1 # RED
          - fe4062eac43d4ea75955f8ae48adcf1e # STRP
          # French Streaming Services
          - b0d6195c23ae254932da00512db7e8a8 # AUViO
          - f27d46a831e6b16fa3fee2c4e5d10984 # MyCANAL
          - 0455d6519a550dbf648c97b56e7231d2 # SALTO
        assign_scores_to:
          - name: WEB-2160p
            score: 0
```

Could be replaced just by a few lines  
```
custom_format_groups:
  - trash_guide:
      - id: b4b4f2aa25c96620b73a01e6242f9dd2 # [Streaming Services] Anime
      - id: ddab3095a5d2f436f369263840af34f9 # [Streaming Services] UK
      - id: 7832db22b71ab669458c17a2850d6913 # [Streaming Services] Miscellaneous
      - id: 848fd356c200568fc5a6248150e7e7ea # [Streaming Services] French
    assign_scores_to:
      - name: WEB-2160p
        score: 0
```

**Comment by BlackDark** [comment]
Released `1.16.0` feel free to test stuff.

**Comment by btTeddy** [comment]
> Released `1.16.0` feel free to test stuff.

It works as expected, but the behaviour is not ideal.

Example:
```
    custom_format_groups:
      - trash_guide:
        - id: f4f1474b963b24cf983455743aa9906c # [Optional] Movie Versions
          include_unrequired: true
        assign_scores_to:
        - name: SQP-4
          score: 0
    custom_formats:
      - trash_ids:
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
        assign_scores_to:
          - name: SQP-4
```

 Group CF `f4f1474b963b24cf983455743aa9906c # [Optional] Movie Versions` adds a few CFs including `e0c07d59beb37348e975a930d5e50319 # Criterion Collection` 

[f4f1474b963b24cf983455743aa9906c ](https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/optional-movie-versions.json)
[e0c07d59beb37348e975a930d5e50319](https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf/criterion-collection.json)

`custom_formats:` section should add the same CF `e0c07d59beb37348e975a930d5e50319 `, but the default score 25 is ignored. `score: 0 is assigned to that CF

<img width="395" height="45" alt="Image" src="https://github.com/user-attachments/assets/20b7db5a-9fc4-4520-8266-f10d1da66444" />

The way it works right now pretty much invalidates scoring in ready-made templates.

Ideally, the score should be assigned as per default value from `custom_formats` section or just overwritten by the following additions of that CF

Hope that makes some sense .
