### ISSUE TITLE
Bug: GitError: fatal: detected dubious ownership in repository at '/app/repos/recyclarr-config'

### ISSUE THREAD

**Issue by clementcohen** [raydak-labs/configarr#239]
HI, 
Unable to get it to work the  1.13.2 version ( same with latest) wit the errror mentionned in  title. 

I use sample  yaml provided in  the website ([Kubernetes documentation](https://configarr.raydak.de/docs/installation/kubernetes) )
```yaml
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: configarr
spec:
  schedule: "0 * * * *" # Runs every hour
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: configarr
              image: ghcr.io/raydak-labs/configarr:1.13.2
              imagePullPolicy: Always
              tty: true # for color support
              envFrom:
                - configMapRef:
                    name: common-deployment-environment
              volumeMounts:
                - mountPath: /app/repos # Cache repositories
                  name: app-data
                  subPath: configarr-repos
                - name: config-volume # Mount specific config
                  mountPath: /app/config/config.yml
                  subPath: config.yml
                - name: secret-volume
                  mountPath: /app/config/secrets.yml # Mount secrets
                  subPath: secrets.yml
          volumes:
            - name: app-data
              persistentVolumeClaim:
                claimName: nas-config-configarr
            - name: config-volume
              configMap:
                name: configarr
            - name: secret-volume
              secret:
                secretName: configarr
          restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configarr
data:
  config.yml: |
    sonarrEnabled: true
    radarrEnabled: false
    whisparrEnabled: false
    readarrEnabled: false
    lidarrEnabled: false
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      series:
        base_url: http://sonarr:8989
        api_key: !secret SONARR_API_KEY

        quality_definition:
          type: series

        include:
          # WEB-1080p
          - template: sonarr-quality-definition-series
          - template: sonarr-v4-quality-profile-web-1080p
          - template: sonarr-v4-custom-formats-web-1080p

          # WEB-2160p
          - template: sonarr-v4-quality-profile-web-2160p
          - template: sonarr-v4-custom-formats-web-2160p

        custom_formats: []
    radarr: {}

```

anything wrong with that ?

BR

**Comment by BlackDark** [comment]
Hi @clementcohen 

Git is very picky about permissions of files and folders.
Can you try to set the user/group in the security context like


```yml
# ...
      template:
        spec:
          securityContext:
            # configure here your user of the existing mount volume
            runAsUser: 1000
            runAsGroup: 3000
            fsGroup: 2000
          containers:
            - name: configarr
              image: ghcr.io/raydak-labs/configarr:1.13.2
              imagePullPolicy: Always
              tty: true # for color support
              envFrom:
                - configMapRef:
```

Maybe I could add some git flags to ignore the ownerships and just allow any user/group to work with. But I think setting the correct user will help you.

**Comment by clementcohen** [comment]
Hi  thanks for the short reply, 
It helps me  to found the issue, it's because my PVC is  a NFS Share provided  by  synology,  so on my security context I had to set the same user and now it works :)  I put this one: 
```yaml
      template:
        spec:
          securityContext:
            runAsUser: 1024
            runAsGroup: 100
            fsGroup: 100
```
