### ISSUE TITLE
Unable to set correct quality_definition

### ISSUE THREAD

**Issue by rabonarca** [raydak-labs/configarr#250]
Hello,

Here is what I am tying to achieve:
```
radarr:
  radarr:
    base_url: http://radarr:7878
    api_key: !env RADARR_API_KEY

    quality_definition:
      type: anime
```

The quality_definition is set successfully in radarr but the values are wrong (They are the one from sonarr anime).

The following code does not check for arrType but assumes that anime is always sonarr.
https://github.com/raydak-labs/configarr/blob/c6ba97dabb8d9569dcf0aac1a11060880c4e186c/src/index.ts#L96-L108

Furthermore it would be impossible to set sqp-streaming or sqp-uhd quality-size.

I am on version 1.13.3

Thanks for your great work !

**Comment by P4rcev4l** [comment]
I have the same problem, trying to include them from TRASH doesn't work either:
```yml
include:
    - template: c2aa9540a57d273a9e03a538efe0ca1b
      source: TRASH
```
```bash
WARN  [19:05:16.475]: Included 'TRASH' template: c2aa9540a57d273a9e03a538efe0ca1b not found.
```
https://github.com/TRaSH-Guides/Guides/blob/7e6c82634bd4bea250d5fc078c67302cd6c31475/docs/json/radarr/quality-size/anime.json
