### ISSUE TITLE
feat: Support *arr setting "Minimum Custom Format Score Increment"

### ISSUE THREAD

**Issue by gnosticJade** [raydak-labs/configarr#265]
Sonarr and Radarr both have a setting in their quality profiles: "Minimum Custom Format Score Increment". This setting allows you to define a minimum improvement in custom score to download an upgrade. Is it possible to define this setting in Configarr and have it enforced upon sync? I was unable to locate any setting or code related to setting this value, nor any issues/PRs for it.

Justification: A common issue I'm encountering with TRASH profiles is that they have scoring for individual release sources; some release groups do not include the source (eg. CR, MAX, DSNP) in their own uploads, but when _the same release_ gets uploaded to a different tracker/indexer, they include the source, which causes the *arr to "upgrade" to an identical release (hash and all). 
Example: Any anime release by the group [SubsPlease], which only uploads Crunchyroll releases (tagged CR). The release `[SubsPlease] mono - 06 (1080p) [9C6525F7]` has a score of 400, while `Mono.S01E06.1080p.CR.WEB-DL.AAC2.0.H.264-SubsPlease` has a score of 406, as the `CR` format applies a +6 score. These files, other than the file name, are identical, but Sonarr sees `.CR.` and applies an additional custom filter score to it.

As a short term workaround, I can set the custom format scoring for individual sources like `CR` to 0, but that's a sub-optimal workaround, as different sources could genuinely be a consideration between given releases when available, such as on media that isn't recently released.

I suspect the best place to implement this definition would be under the `quality_profile` directive, alongside `min_format_score` and `until_score`.
```
    quality_profiles:
      - name: ExampleProfile
        upgrade:
          min_format_score: 200
          minimum_upgrade_increment: 100
          until_score: 1000
```

**Comment by BlackDark** [comment]
Hi @gnosticJade, should be the following values (yes, same naming but value under the upgrade object, not the best :D ):

```yaml
quality_profiles:
  - name: ExampleProfile
    reset_unmatched_scores:
      enabled: true
    upgrade:
      allowed: true
      until_quality: WEB 2160p
      until_score: 1000
      min_format_score: 5 # this one should be the increment value
    min_format_score: 0 # this is the minimum custom format
```
