### ISSUE TITLE
Feat: allow changing the default score for a trash custom format

### ISSUE THREAD

**Issue by Splinter7914** [raydak-labs/configarr#278]
There are a few format's where i like to change the score. Any time this happens I have to take that format out and add an explicit

```
- trash_ids:
        - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
        assign_scores_to:
          - name: name-1
            score: 10000
          - name: name-2
            score: 10000
          - name: name-3
            score: 10000
```

If we have multiple such format's it ends up adding quite a few lines to the config files and makes it 

I was wondering if the list of trash id's being added could support being able to specify the score for example something like or something similar where we could specify the score we want as part of the list of id's we want to add.

```
- trash_ids:
        - e23edd2482476e595fb990b12e7c609c # DV HDR10
        - c53085ddbd027d9624b320627748612f # DV HDR10+
        - id: 496f355514737f7d83bf7aa4d24f8169
           score: 10000
```
