### ISSUE TITLE
Feat: Possibility to append ISO-2 country to media_naming key

### ISSUE THREAD

**Issue by RealRen0** [raydak-labs/configarr#280]
In Radarr, it's possible to customize movie naming by appending an ISO-2 country code (e.g., {Movie CleanTitle:de}), which is also documented in the German TRaSH Guide.

However, Configarr is currently limited to using the keys provided by the TRaSH Guides, which do not support country code variations ([see radarr-naming.json](https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/naming/radarr-naming.json)).

I’d like to propose adding support for appending ISO-2 country codes to these keys in Configarr. This would allow users to define localized naming schemes. For example:
```
media_naming:
  folder: jellyfin-tmdb:de
  movie:
    rename: true
    standard: default:de
```
This enhancement would bring Configarr more in line with Radarr’s capabilities and offer greater flexibility for international users.
