### ISSUE TITLE
API keys as environment variables

### ISSUE THREAD

**Issue by chrisb86** [raydak-labs/configarr#60]
The *arrs support the badly documented way to provide config settings per env variables now.

By setting for example $SONARR__APP__INSTANCENAME or $SONARR__AUTH__APIKEY you can define API keys and stuff by runtime. Is there a way to make use of the environment variables so far?

**Comment by BlackDark** [comment]
Hey there, what exactly would you try to accomplish? 
Full configuration only via env vars would be too complicated because of the different configs available. 
Or do want a way to provide the API key instead of using an own secrets file?

**Comment by chrisb86** [comment]
Yeah, the latter. I would like to pass the API key as env var instead of the secrets file so I can set it globally for my stack.

**Comment by BlackDark** [comment]
Add an MR with which you can define something like this in the `config.yml`:

```yaml
sonarr:
  series:
    base_url: http://localhost:8989
	# This will load the value from the env var SONARR_API_KEY
    api_key: !env SONARR_API_KEY
```

With this approach we have lot of flexibility I think. What's your opinion?
