### ISSUE TITLE
v1.0.0 Renamed the wrong `quality_profiles` to `assign_scores_to`

### ISSUE THREAD

**Issue by raldone01** [raydak-labs/configarr#69]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
localCustomFormatsPath: /app/cfs
localConfigTemplatesPath: /app/templates

# Configuration specific to Sonarr
sonarr:
  anime:
    base_url: http://sonarr-anime:8989
    api_key: !secret SONARR_ANIME_API_KEY
    assign_scores_to: # quality_profiles should be here
      - name: Remux-2160p - Anime
        quality_sort: top
        score_set: anime-sonarr
        upgrade: &upgrade
          allowed: true
          until_quality: SINGLE_STAGE
          until_score: 5000000
        qualities: &sonarr-remux-2160p-qualities
          - name: SINGLE_STAGE
            enabled: true
            qualities:
              - Bluray-2160p
              - SDTV
          - name: Unknown
            enabled: false
            qualities:
              - Unknown
    custom_formats:
      - trash_ids:
          - custom-german-dl # Boost German DL
          - custom-german-dl-2 # Boost German DL
        quality_profiles: # assign_scores_to should be here
          - name: Remux-2160p - Anime
```

The above config works but it should only work if `quality_profiles`and `assign_scores_to` is switched.

The correct case does not work.

Thank you for your work.
