### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by BlackDark** [raydak-labs/configarr#9]
Feel free to provide feedback in this issue or feature requests.
Or just create a new issue for now :)

## Possible ideas:

- [x] keep support for syncing trash guides
  - I like the possible configuration in recyclarr but I miss some features
- [x] add support for local configuration to include
  - I don't want to fork a project to add custom things to it
- [ ] Maybe an free GUI to sync your stuff
- [ ] Add additional best configuration for different languages/countries like Germany
- [x] Define CustomFormats directly in configuration maybe something like (directly translated JSON -> YAML?)
  Not sure if useful if we already have to capability to provide own formats via JSON folder (additional those JSON are directly compatible with UI Import)
  ```yaml
  customFormats:
  - name: NewCF
    score: 125
    includeCustomFormatWhenRenaming: false
    specifications:
    - name: Size
      implementation: SizeSpecification
      negate: false
      required: true
      fields:
        min: 1
        max: 9
  ```

## Work TODOs

- [ ] Optimize types. Generated ones work for first step but not very optimal because they do not correctly represent request/response types.
- [x] Default scores from trash guide
- [x] Radarr support
- [x] Debug logging switchable
- [x] Improved Diff output
- [ ] Feature completion with recyclarr
- [x] Cross references to:
  - [x] https://github.com/PCJones/radarr-sonarr-german-dual-language
  - [x] https://github.com/PCJones/usenet-guide
- [x] Build docker container
- [x] Build multi arch containers
- [x] Add Github Actions stuff
- [x] Improve code & tidy up lint errors
- [x] write docs for running with container
  - [x] Plain docker
  - [x] Kubernetes
- [ ] Simple Config validation
- [x] Local recyclarr templates to include
- [ ] Clone existing templates: Lets say you want the same template but with a different name?
- [x] Add better documentation (probably better as separate site or wiki with https://docusaurus.io/)
- [x] https://recyclarr.dev/wiki/yaml/config-reference/quality-definition/#qd-preferred-ratio missing #98

**Comment by raldone01** [comment]
```
"trash_scores": {
    "default": -10000
  },
```

I added custom format json files.
They get imported fine but the default score seems to be ignored.

```
custom_formats:
      # WEB-1080p
      # Optional
      - trash_ids:
          # custom german dl
          - custom-german-mic-dub # Avoid German Mic Dub
          - custom-german-dl      # Boost German DL
          - custom-german-dl-2    # Boost German DL
          - custom-english-only   # English+German > English Only > German Only
        quality_profiles:
          - name: WEB-1080p
```

I provided default scores in each but they all get added with score 0.

**Comment by BlackDark** [comment]
Some question:
- the CF itself got created?
- anything in the logs?


Here are my tests:

```
# The CF
{
  "trash_id": "test-cf",
  "trash_scores": {
    "default": -10000
  },
  "name": "TEST CF",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Size",
      "implementation": "SizeSpecification",
      "negate": true,
      "required": false,
      "fields": {
        "min": 0,
        "max": 100
      }
    }
  ]
}

# in the config or template
...
    custom_formats:
      - trash_ids:
          - test-cf
        quality_profiles:
          - name: Default (DE)
...
```

![image](https://github.com/raydak-labs/configarr/assets/9947112/65e414dd-fcda-40e7-8815-491d12358439)

**Comment by raldone01** [comment]
I will create a stripped down example when I get the time. I will also try to include quality profiles as it did not seem to sync the order correctly.

**Comment by muhmuhhum** [comment]
would be nice to have support for other arr stack apps like readarr, whisparr

**Comment by BlackDark** [comment]
> would be nice to have support for other arr stack apps like readarr, whisparr

Hi @muhmuhhum  have added #102 and #103 and will take a look. If the API is the same implementation should be straight forward. Downside is, that no default configurations/templates are provided by trash guide so everything has to be done by users themself.

**Comment by mrMightyM** [comment]
I am having a couple of different issues, and I'm not sure the best place to ask.

In config.yml, I have the following:

```
sonarr:
  instance1:
    include:
      - template: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
        source: TRASH
      - template: sonarr-cf
      - template: sonarr-quality
```
In templates/sonarr-quality.yml
```
quality_profiles:
  - name: "WEB-1080p"
    upgrade:
      allowed: true
      until_quality: Bluray-1080p
      until_score: 10000
    min_format_score: 0
    quality_sort: top
    qualities:
      - name: Bluray-1080p
      - name: WEBRip-1080p
        qualities:
          - WEBDL-1080p
          - WEBRip-1080p
      - name: WEB 720p
        qualities:
          - WEBDL-720p
          - WEBRip-720p
```
What I would expect is it to import the template from TRASH, then update it with my settings from sonarr-quality.yml, but all it does is import it from TRASH and ignores the template. in the Debug log I get:
```
DEBUG [09:50:24.493]: QualityProfile (WEB-1080p) - In Sync: true, CF Changes: false, Some other diff: false
INFO  [09:50:24.493]: QualityProfiles: Create: 0, Update: 0, Unchanged: 1

```
If I remove template: sonarr-quality and put everything directly into config.yml it works as expected.
If I don't import from TRASH, it reads and imports everything from sonarr-quality.yml

Am I misunderstanding something?

Second issue I am having is in config.yml
```
    custom_format_groups:
      - trash_guide:
          - id: 7832db22b71ab669458c17a2850d6913 # [Streaming Services] Miscellaneous
        assign_score_to:
          - name: "WEB-1080p"

```
It pulls and assigns everything from Miscellaneous Streaming Services to the WEB-1080p profile, but with a score of 0, instead of the default scores listed in the cf-group. If I each one manually into template/sonar-cf.yml, everything works as expected with is assigning default scores to each service.

If I need to post this elsewhere let me know, otherwise Thank you!

**Comment by BlackDark** [comment]
Hi @mrMightyM  i created an issue out of your comment: https://github.com/raydak-labs/configarr/issues/204

Will investigate it.

**Comment by BlackDark** [comment]
@mrMightyM 

for your seccond issue, because all CFs in the group are not required you have to manually set the flag to include them:

```yml
    custom_format_groups:
      - trash_guide:
          - id: 7832db22b71ab669458c17a2850d6913 # [Streaming Services] Miscellaneous
            include_unrequired: true # if you want to load all set this to true
        assign_scores_to:
          - name: WEB-1080p
```

**Comment by mrMightyM** [comment]
The second issue was a typo on my end, and you can see it above, I had assign_score_to instead of assign_scores_to, that plus the include_unrequired seems to have fixed that.

I have re-checked everything else, but the first issue still remains.

Thank you!

**Comment by BlackDark** [comment]
> @BlackDark
> 
> The second issue was a typo on my end, and you can see it above, I had assign_score_to instead of assign_scores_to, that plus the include_unrequired seems to have fixed that.
> 
> I have re-checked everything else, but the first issue still remains.
> 
> Thank you!
> 
> 

Did you try the latest version? I released one some hours ago.

**Comment by mrMightyM** [comment]
> > [@BlackDark](https://github.com/BlackDark)
> > The second issue was a typo on my end, and you can see it above, I had assign_score_to instead of assign_scores_to, that plus the include_unrequired seems to have fixed that.
> > I have re-checked everything else, but the first issue still remains.
> > Thank you!
> 
> Did you try the latest version? I released one some hours ago.

Yes, I had to force docker to pull the new image, and it is now working as I would expect. I realized later I was also having the same issue with Radarr and it has fixed both

Thanks again!

**Comment by astappiev** [comment]
Add ability to rename profiles on import, e.g.
```yaml
include:
  - template: dca7e5e9e99c703bcbdaaa471dd40e98 # german-hd-bluray-web.json
    source: TRASH
    rename: 1080p (German)
  - template: 7324309a7d1e10dc0dc2cea6c70ed852 # german-uhd-bluray-web-alternative.json
    source: TRASH
    rename: 2160p (German)
  - template: 9d142234e45d6143785ac55f5a9e8dc9 # web-1080p-alternative.json
    source: TRASH
    rename: 1080p
  - template: dfa5eaae7894077ad6449169b6eb03e0 # web-2160p-alternative.json
    source: TRASH
    rename: 2160p
```

**Comment by soredake** [comment]
Configarr correctly imports custom profiles but default score is not set in any profile:

![Image](https://github.com/user-attachments/assets/20a1917d-7342-4c08-93b0-8b7222131df0)

<details>
<summary>config</summary>
```yaml
#trashGuideUrl: https://github.com/BlackDark/fork-TRASH-Guides
#recyclarrConfigUrl: https://github.com/BlackDark/fork-recyclarr-configs
localCustomFormatsPath: /app/cfs
localConfigTemplatesPath: /app/templates

# You can enable or disable
sonarrEnabled: true
radarrEnabled: true

sonarr:
  main:
    # Set the URL/API Key to your actual instance
    base_url: http://sonarr:8989
    api_key: 

    quality_definition:
      type: series

    custom_formats:
      # General
      # Retags: https://github.com/TRaSH-Guides/Guides/issues/2251
      - trash_ids:
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Repack v3
          - 3a4127d8aa781b44120d907f2cd62627 # Hybrid
          - b735f09d3c025cbb7d75a5d38325b73b # Remaster
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
          - 23297a736ca77c0fc8e70f8edd7ee56c # Upscaled
          #          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
          - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene
        assign_scores_to:
          - name: Any
          - name: HD - 720p/1080p
          - name: HD-720p
          - name: HD-1080p
          - name: Up to 1080p - HEVC Preferred
          - name: SD
          - name: Ultra-HD
          - name: Ultra-HD - Rips only
          - name: Ultra-HD - WEBRips only

      # HEVC
      - trash_ids:
          - c9eafd50846d299b862ca9bb6ea91950 # x265
        assign_scores_to:
          - name: Up to 1080p - HEVC Preferred
            score: 10000

      # 10bit
      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: Up to 1080p - HEVC Preferred
            score: 2500

      # 1080p HQ Release Groups
      - trash_ids:
          - d6819cba26b1a6508138d25fb5e32293 # HD Bluray Tier 01
          - c2216b7b8aa545dc1ce8388c618f8d57 # HD Bluray Tier 02
        assign_scores_to:
          - name: Any
          - name: HD - 720p/1080p
          - name: HD-720p
          - name: HD-1080p
          - name: Up to 1080p - HEVC Preferred

radarr:
  main:
    # Set the URL/API Key to your actual instance
    base_url: http://radarr:7878
    api_key: 

    # experimental
    # media_management:
    #   recycleBin: "/tmp"

    # experimental
    # media_naming_api: {}

    # naming from TRaSH. See docs
    # media_naming: {}

    # quality_definition:
    #   type: movie

    custom_formats:
      # General
      - trash_ids:
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          - 5caaaa1c08c1742aa4342d8c4cc463f2 # Repack3
          - 0f12c086e289cf966fa5948eac571f44 # Hybrid
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - cae4ca30163749b891686f95532519bd # AV1
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
        assign_scores_to:
          - name: Any
          - name: Any (LQ, Upscale, Retags allowed)
          - name: HD - 720p/1080p
          - name: HD-720p
          - name: HD-1080p
          - name: Up to 1080p - HEVC Preferred
          - name: SD
          - name: Ultra-HD
          - name: Ultra-HD - Rips only

      # LQ, Upscale, Retags
      # Retags: https://github.com/TRaSH-Guides/Guides/issues/2251
      - trash_ids:
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
          #- 5c44f52a8714fdd79bb4d98e2673be1f # Retags
        assign_scores_to:
          - name: Any (LQ, Upscale, Retags allowed)
            score: 0
          - name: Any
          - name: SD
          - name: HD - 720p/1080p
          - name: HD-720p
          - name: HD-1080p
          - name: Up to 1080p - HEVC Preferred
          - name: Ultra-HD
          - name: Ultra-HD - Rips only

      # 4K HQ Release Groups
      - trash_ids:
          - 4d74ac4c4db0b64bff6ce0cffef99bf0 # UHD Bluray Tier 01
          - a58f517a70193f8e578056642178419d # UHD Bluray Tier 02
          - e71939fae578037e7aed3ee219bbe7c1 # UHD Bluray Tier 03
        assign_scores_to:
          - name: Any
          - name: Ultra-HD
          - name: Ultra-HD - Rips only

      # HEVC
      - trash_ids:
          - 9170d55c319f4fe40da8711ba9d8050d # x265
        assign_scores_to:
          - name: Up to 1080p - HEVC Preferred
            score: 10000

      # 10bit
      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Up to 1080p - HEVC Preferred
            score: 2500

      # 1080p HQ Release Groups
      - trash_ids:
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
        assign_scores_to:
          - name: Any
          - name: HD - 720p/1080p
          - name: HD-720p
          - name: HD-1080p
          - name: Up to 1080p - HEVC Preferred
 ```
</details>

**Comment by BlackDark** [comment]
> [@BlackDark](https://github.com/BlackDark) configarr correctly imports custom profiles but default score is not set in any profile:
> 
> ![Image](https://github.com/user-attachments/assets/20a1917d-7342-4c08-93b0-8b7222131df0)
> config

Hi, where do you define your profiles? You need to define them so that they will be "managed" by configarr.

**Comment by stargater500** [comment]
I'm having similar difficulties with scoring on a custom profile.  What I'm trying to do is, in addition to having the two TRASH profiles (WEB-1080p and WEB-2160p), also have a custom profile that is fully defined in the config _except_ that it should use the scoring from the TRASH WEB-1080p profile, and then also allow overriding specific scores.  I can get everything but the scoring to work.  The scores are always zero (except for my manually defined overrides).  I've tried using `score_set` and a couple other things along the way but can't seem to find a way to get a custom profile defined in the config to use the scores of an externally defined profile.  What am I missing? 

<details>
  <summary>config section</summary>
  
  ```yaml
sonarr:
  series: # instance name
    enabled: true # can set false to exclude configarr from syncing with this instance
    # Set the URL/API Key to your actual instance
    base_url: http://redacted:8989
    api_key: !secret SONARR_API_KEY

    include:
      #### WEB-1080p
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

      #### WEB-2160p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p

    quality_profiles:
      - name: WEB-1080p/720p-base
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Web 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: Bluray-1080p
          - name: HDTV-1080p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: Bluray-720p
          - name: HDTV-720p

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series
      qualities:
        - quality: "HDTV-1080p"
          min: 15
          preferred: 35
          max: 90
        - quality: "WEBRip-1080p"
          min: 15
          preferred: 35
          max: 90
        - quality: "WEBDL-1080p"
          min: 15
          preferred: 35
          max: 90
        - quality: "Bluray-1080p"
          min: 50.4
          preferred: 70
          max: 90
        - quality: "HDTV-720p"
          min: 10
          preferred: 25
          max: 90
        - quality: "WEBRip-720p"
          min: 10
          preferred: 25
          max: 90
        - quality: "WEBDL-720p"
          min: 10
          preferred: 25
          max: 90
        - quality: "Bluray-720p"
          min: 17.1
          preferred: 30
          max: 60

    custom_formats: # Custom format assignments
      - trash_ids:
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD) (this is the ID from TRaSH-Guides)
        assign_scores_to:
          - name: WEB-1080p/720p-base
            score: 10 # New scoring
  ```
  
</details>

**Comment by BlackDark** [comment]
> I'm having similar difficulties with scoring on a custom profile. What I'm trying to do is, in addition to having the two TRASH profiles (WEB-1080p and WEB-2160p), also have a custom profile that is fully defined in the config _except_ that it should use the scoring from the TRASH WEB-1080p profile, and then also allow overriding specific scores. I can get everything but the scoring to work. The scores are always zero (except for my manually defined overrides). I've tried using `score_set` and a couple other things along the way but can't seem to find a way to get a custom profile defined in the config to use the scores of an externally defined profile. What am I missing?
> config section

Hi @stargater500, not sure if it your correct yaml you have but the indentation is not fully correct. For me I tested your example and it seems to work.
The trash profiles (web180p + web2160p) are fully scored and your custom profile has the one score set with -10k.

<img width="1047" alt="Image" src="https://github.com/user-attachments/assets/0ea0689a-afac-412d-b198-657684670307" />

<details><summary>Details</summary>
  
  ```yaml
radarrEnabled: false
whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

sonarr:
  instance1:
    base_url: http://sonarr:8989
    api_key: !secret SONARR_API_KEY

    quality_definition:
      type: series

    include:
      #### WEB-1080p
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

      #### WEB-2160p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p

    quality_profiles:
      - name: WEB-1080p/720p-base
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Web 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: Bluray-1080p
          - name: HDTV-1080p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: Bluray-720p
          - name: HDTV-720p

    custom_formats:
      - trash_ids:
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD) (this is the ID from TRaSH-Guides)
        assign_scores_to:
          - name: WEB-1080p/720p-base
            # default score is -10000 so the score is at the bottom of the profile  in UI
            # score: 0 # Uncomment this line to change score
```
</details>
